services:

  postgres:
    image: postgres:15-alpine
    container_name: piped-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: piped
      POSTGRES_USER: piped
      POSTGRES_PASSWORD: Piped-QNAP-xxxx-ChangeMe

    volumes:
      - /share/Container/piped/data/postgres:/var/lib/postgresql/data

    networks:
      - piped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U piped -d piped"]
      interval: 10s
      timeout: 5s
      retries: 10


  piped-backend:
    image: 1337kavin/piped:latest
    container_name: piped-backend
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - /share/Container/piped/config/config.properties:/app/config.properties:ro

    networks:
      - piped

  piped-bg-helper:
    image: 1337kavin/bg-helper-server:latest
    container_name: piped-bg-helper
    restart: unless-stopped

    networks:
      - piped
      
  piped-proxy:
    image: 1337kavin/piped-proxy:latest
    container_name: piped-proxy
    restart: unless-stopped

    environment:
      UDS: "0"

    networks:
      - piped


  piped-frontend:
    image: 1337kavin/piped-frontend:latest
    container_name: piped-frontend
    restart: unless-stopped

    environment:
      BACKEND_HOSTNAME: pipedapi.home:18080
      HTTP_MODE: http

    depends_on:
      - piped-backend

    networks:
      - piped


  nginx:
    image: nginx:mainline-alpine
    container_name: piped-nginx
    restart: unless-stopped

    depends_on:
      - piped-backend
      - piped-proxy
      - piped-frontend

    ports:
      - "18080:80"

    volumes:
      - /share/Container/piped/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - /share/Container/piped/config/pipedfrontend.conf:/etc/nginx/conf.d/pipedfrontend.conf:ro
      - /share/Container/piped/config/pipedapi.conf:/etc/nginx/conf.d/pipedapi.conf:ro
      - /share/Container/piped/config/pipedproxy.conf:/etc/nginx/conf.d/pipedproxy.conf:ro
      - /share/Container/piped/config/ytproxy.conf:/etc/nginx/snippets/ytproxy.conf:ro

    networks:
      - piped


networks:
  piped:
    name: piped
    driver: bridge