PORT:8080
HTTP_WORKERS:2

PROXY_PART:https://pipedproxy.home:18080
API_URL:https://pipedapi.home:18080
FRONTEND_URL:https://piped.home:18080

#CAPTCHA_BASE_URL:https://api.capmonster.cloud/
#CAPTCHA_API_KEY:

COMPROMISED_PASSWORD_CHECK:true

DISABLE_REGISTRATION:false

FEED_RETENTION:30

DISABLE_TIMERS:true

RYD_PROXY_URL:https://ryd-proxy.kavin.rocks
DISABLE_RYD:false

SPONSORBLOCK_SERVERS:https://sponsor.ajay.app,https://sponsorblock.kavin.rocks

DISABLE_LBRY:false

SUBSCRIPTIONS_EXPIRY:30

CONSENT_COOKIE:true

DISABLE_SERVER:false

MATRIX_SERVER:https://matrix-client.matrix.org

hibernate.connection.url:jdbc:postgresql://postgres:5432/piped
hibernate.connection.driver_class:org.postgresql.Driver
hibernate.dialect:org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.username:piped
hibernate.connection.password:Piped-QNAP-xxxx-ChangeMe