upstream piped_frontend {
    server piped-frontend:80;
}

server {
    listen 443 ssl; # Cambiado a ssl listen 80;
    server_name piped.home;
    
    # 🔑 Los mismos certificados que ya generamos
    ssl_certificate /etc/ssl/certs-custom/piped.crt;
    ssl_certificate_key /etc/ssl/certs-custom/piped.key;    
    # ssl_certificate /etc/ssl/certs/piped.crt;
    # ssl_certificate_key /etc/ssl/private/piped.key;
    
    # 🔒 CONFIGURACIÓN SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
        
    location / {
        proxy_pass http://piped_frontend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
    }
}

# 🔄 OPCIONAL: Redirigir si por error intentas entrar por HTTP (Puerto 80)
server {
    listen 80;
    server_name piped.home;
    return 301 https://$host:18080$request_uri; 
}