PORT:8080
HTTP_WORKERS:2

PROXY_PART:http://pipedproxy.home:18080
API_URL:http://pipedapi.home:18080
FRONTEND_URL:http://piped.home:18080

#CAPTCHA_BASE_URL:https://api.capmonster.cloud/
#CAPTCHA_API_KEY:

# BG_HELPER_URL:http://piped-bg-helper:3000
BGUTIL_BASE_URL: http://piped-bgutil:4416

COMPATIBLE_VIDEO_LINKS=true

COMPROMISED_PASSWORD_CHECK:true

DISABLE_REGISTRATION:false

FEED_RETENTION:30

DISABLE_TIMERS:true

RYD_PROXY_URL:https://ryd-proxy.kavin.rocks
DISABLE_RYD:false

SPONSORBLOCK_SERVERS:https://sponsor.ajay.app,https://sponsorblock.kavin.rocks

DISABLE_LBRY:false

SUBSCRIPTIONS_EXPIRY:30

CONSENT_COOKIE:true

DISABLE_SERVER:false

#MATRIX_SERVER:https://matrix-client.matrix.org

hibernate.connection.url:jdbc:postgresql://postgres:5432/piped
hibernate.connection.driver_class:org.postgresql.Driver
hibernate.dialect:org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.username:piped
hibernate.connection.password:Piped-QNAP-xxxx-ChangeMe

# Asegúrate de que apunte al contenedor interno de Docker y su puerto correcto
video_resolver_url=http://piped-resolver:8000

# Asegúrate de que el backend use el proveedor de tokens POT para evitar bloqueos de Youtube
yt_dl_pot_provider_url=http://piped-bgutil:8080

# Configuración obligatoria para corregir el fallo de MatrixHelper
#MATRIX_SERVER=https://matrix.org
#MATRIX_ROOM_ID=!falseroomid:matrix.org
#MATRIX_ACCESS_TOKEN=syt_fakedummytokendontdelete_123456789