upstream piped_proxy {
    server piped-proxy:8080;
}

server {
    listen 80;
    server_name pipedproxy.home;

    # Permitir que las respuestas de vídeo sean grandes para resoluciones 1080p o 4K
    proxy_buffers 8 16k;
    proxy_buffer_size 32k;

    location ~ (/videoplayback|/api/v4/|/api/manifest/) {
        include /etc/nginx/snippets/ytproxy.conf;
        add_header Cache-Control private always;
        proxy_hide_header Access-Control-Allow-Origin;
    }

    location / {
        include /etc/nginx/snippets/ytproxy.conf;
        add_header Cache-Control "public, max-age=604800";
        proxy_hide_header Access-Control-Allow-Origin;
    }
}